In [1]:
#Neden  Numpy?  -Hız. Vektör seviyesinde işlem
#İki listenin elemanları çarpılıp ayrı bir listede tutulacak.
#Listeyi numpy array ine çevirme:
import numpy as np

a=[1,2,3,4]
b=[2,3,4,5]

a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

In [2]:
#Numpy arrayi oluşturma- liste üzerinden
np.array([1,2,3,4])
type(np.array([1,2,3,4]))


numpy.ndarray

In [4]:
#10 adet 10 lardan oluşan, tipi int olan np arrayi oluşturma
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# 0- 10 arası rastgele 10 adet int seçerek np arrayi oluşturma
#random.randint fonksiyonu:
np.random.randint(0,10, size=10)

array([1, 9, 6, 5, 9, 9, 3, 9, 8, 6])

In [7]:
#normal(mean, std,(size x size)) fonksiyonu
#Ortalaması 10, standard sapması 4 olan normal dağılımlı 3 satır 4 sutunlu array
np.random.normal(10, 4, (3, 4))

array([[15.33591393, 13.60410122,  3.58133385, 10.52750255],
       [14.24921187,  7.81438827, 12.1103359 ,  8.51278753],
       [11.07362164,  8.60250596, 16.85959156,  3.22766986]])

In [8]:
#Numpy array inin özellikleri
a=np.random.randint(10, size=5)
print(a)

[6 0 4 0 0]


In [7]:
#Boyut Sayısı
a.ndim

1

In [9]:
#Boyut Bilgisi
a.shape

(5,)

In [10]:
#Eleman sayısı
a.size

5

In [11]:
#İçinde tuttuğu verilerin tipi
a.dtype

dtype('int32')

In [12]:
#Numpy arrayinin boyutunu değiştirmek için : reshape
#Tek boyutlu bir array oluşturduk
np.random.randint(1, 10, size=9)

array([5, 2, 5, 5, 5, 1, 6, 2, 1])

In [2]:
#Tek boyutlu arrayi iki boyutlu arraye dönüştür
import numpy as np
np.random.randint(1, 10, size=9).reshape(3,3)

array([[4, 1, 6],
       [5, 4, 6],
       [5, 3, 2]])

In [5]:
#Numpy arraylerinde ındex seçimi, slicing
a=np.random.randint(1, 10, size=6)
a[0]
a[0:5]


In [ ]:
#eleman değştirme

In [6]:
a[0]=999
a

array([999,   5,   6,   7,   8,   4])

In [8]:
#İki boyutlu arraylerde seçme işlemi
m=np.random.randint(10, size=(3, 5))
m

array([[6, 1, 9, 8, 3],
       [4, 0, 6, 0, 0],
       [5, 8, 1, 0, 2]])

In [13]:
#0. satır 0. sutundaki eleman
m[0,0]


6

In [ ]:
#İki elemanlı bir dizinin elemsanını değiştirme

In [20]:
m[2,2]=999
m

array([[  6,   1,   9,   8,   3],
       [  4,   0,   6,   0,   0],
       [  5,   8, 999,   0,   2]])

In [21]:
#0 dan 2. satıra kadar git, 0 dan 3. sutuna kadar:
m[0:2, 0:3]

array([[6, 1, 9],
       [4, 0, 6]])

In [23]:
#Fancy Index
#0 dan 30 a kadar 3er 3er artırılan array
np.arange(0, 30, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [25]:
#Şu listedeki indeklere eriş: 2,3,4
v=np.arange(0, 30, 3)
catch=[2,3,4]
v[catch]


array([ 6,  9, 12])

In [26]:
#Numpy da Koşullu İşlemler
#Listede 3 ten küçük olanları seç:
b=np.array([1,2,3,4,5])
b[b<3]

array([1, 2])

In [27]:
b*2

array([ 2,  4,  6,  8, 10])

In [28]:
b*10/2

array([ 5., 10., 15., 20., 25.])

In [29]:
b**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [33]:
#np.subtract : çıkarma
np.subtract(b,1)

array([0, 1, 2, 3, 4])

In [34]:
#ekleme
np.add(b,1)

array([2, 3, 4, 5, 6])

In [35]:
#ortalama : mean
np.mean(b)

3.0

In [36]:
#elemanları toplamı : sum
np.sum(b)

15

In [38]:
np.min(b)

1

In [39]:
np.max(b)

5

In [40]:
#varyans
np.var(b)

2.0

In [ ]:
#Numpy ile İki bilinmeyenli denklem çözümü
5*x0 + x1 =12
x0 + 3*x1=10

In [47]:
#1. denklemdeki değişkenlerin ve 2. denklemdeki değişkenin katsayıları bir listede, sonuçlar ayrı bir listede
a=np.array([[5,1], [1,3]])
b=np.array([12,10])

#linalg.solve
np.linalg.solve(a,b)

array([1.85714286, 2.71428571])

In [48]:
a=np.array([2,4,6,8])
a**2

array([ 4, 16, 36, 64], dtype=int32)

In [1]:
#############PANDAS############# 
#Bir Listeyi Pandas serisi haline getirmek
import pandas as pd
s=pd.Series([12, 34, 72, 34])
s

0    12
1    34
2    72
3    34
dtype: int64

In [2]:
type(s)

pandas.core.series.Series

In [3]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
s.dtype

dtype('int64')

In [5]:
#eleman sayısı
s.size 

4

In [6]:
#boyut sayısı. Pandas serileri tek boyutludur
s.ndim

1

In [7]:
#içindeki değerlere erişmek
s.values

array([12, 34, 72, 34], dtype=int64)

In [8]:
#indeksler önemli değil, numpy arrayi
type(s.values)

numpy.ndarray

In [9]:
s.head(3)

0    12
1    34
2    72
dtype: int64

In [10]:
s.tail(3)

1    34
2    72
3    34
dtype: int64

In [3]:
import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [4]:
#Boyut bilgisi. 891 satır, 15 sutun
df.shape

(891, 15)

In [5]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [6]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [7]:
df.describe().T

count       mean        std   min      25%      50%   75%       max
survived  891.0   0.383838   0.486592  0.00   0.0000   0.0000   1.0    1.0000
pclass    891.0   2.308642   0.836071  1.00   2.0000   3.0000   3.0    3.0000
age       714.0  29.699118  14.526497  0.42  20.1250  28.0000  38.0   80.0000
sibsp     891.0   0.523008   1.102743  0.00   0.0000   0.0000   1.0    8.0000
parch     891.0   0.381594   0.806057  0.00   0.0000   0.0000   0.0    6.0000
fare      891.0  32.204208  49.693429  0.00   7.9104  14.4542  31.0  512.3292

In [9]:
#Herhangi bir değerde eksik var mı?
#values ifadesi kullanılıyorsa = numpy array i
df.isnull().values.any()

True

In [12]:
#Her değişkende kaç tane eksik değer var?
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [16]:
#df içinden değişken seçmek
df["sex"].tail

<bound method NDFrame.tail of 0        male
1      female
2      female
3      female
4        male
        ...  
886      male
887    female
888    female
889      male
890      male
Name: sex, Length: 891, dtype: object>

In [17]:
#Kategorik değişkende her sınıftan kaç tane var?
df["sex"].value_counts()

male      577
female    314
Name: sex, dtype: int64

In [18]:
#Slicing
df[0:13]

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0          0       3    male  22.0      1      0   7.2500        S   Third   
1          1       1  female  38.0      1      0  71.2833        C   First   
2          1       3  female  26.0      0      0   7.9250        S   Third   
3          1       1  female  35.0      1      0  53.1000        S   First   
4          0       3    male  35.0      0      0   8.0500        S   Third   
5          0       3    male   NaN      0      0   8.4583        Q   Third   
6          0       1    male  54.0      0      0  51.8625        S   First   
7          0       3    male   2.0      3      1  21.0750        S   Third   
8          1       3  female  27.0      0      2  11.1333        S   Third   
9          1       2  female  14.0      1      0  30.0708        C  Second   
10         1       3  female   4.0      1      1  16.7000        S   Third   
11         1       1  female  58.0      0      0  26.5500        S   First   
12         0       3    male  20.0      0      0   8.0500        S   Third   

      who  adult_male deck  embark_town alive  alone  
0     man        True  NaN  Southampton    no  False  
1   woman       False    C    Cherbourg   yes  False  
2   woman       False  NaN  Southampton   yes   True  
3   woman       False    C  Southampton   yes  False  
4     man        True  NaN  Southampton    no   True  
5     man        True  NaN   Queenstown    no   True  
6     man        True    E  Southampton    no   True  
7   child       False  NaN  Southampton    no  False  
8   woman       False  NaN  Southampton   yes  False  
9   child       False  NaN    Cherbourg   yes  False  
10  child       False    G  Southampton   yes  False  
11  woman       False    C  Southampton   yes   True  
12    man        True  NaN  Southampton    no   True

In [20]:
#x ekseninden 0. indexi sil
df.drop(0, axis=0).head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   
5         0       3    male   NaN      0      0   8.4583        Q  Third   

     who  adult_male deck  embark_town alive  alone  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True

In [6]:
#İşlemi kalıcı hale getirmek için : ata
df= df.drop(index_del, axis=0)
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
2           1       3  female  26.0      0      0   7.9250        S   Third   
4           0       3    male  35.0      0      0   8.0500        S   Third   
6           0       1    male  54.0      0      0  51.8625        S   First   
8           1       3  female  27.0      0      2  11.1333        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
2    woman       False  NaN  Southampton   yes   True  
4      man        True  NaN  Southampton    no   True  
6      man        True    E  Southampton    no   True  
8    woman       False  NaN  Southampton   yes  False  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[886 rows x 15 columns]

In [13]:
#Ya da INPLACE
cıkar=[2,4,6,8]
df.drop(cıkar, axis=0, inplace=True)
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
1           1       1  female  38.0      1      0  71.2833        C   First   
3           1       1  female  35.0      1      0  53.1000        S   First   
5           0       3    male   NaN      0      0   8.4583        Q   Third   
6           0       1    male  54.0      0      0  51.8625        S   First   
7           0       3    male   2.0      3      1  21.0750        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
1    woman       False    C    Cherbourg   yes  False  
3    woman       False    C  Southampton   yes  False  
5      man        True  NaN   Queenstown    no   True  
6      man        True    E  Southampton    no   True  
7    child       False  NaN  Southampton    no  False  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[888 rows x 15 columns]

In [39]:
#################################Değişkeni Indexe çevirmek####################
#Yaş değişkenini indexe, index teki sayıları da değişken olarak sutuna almak :
#indeks yerine age gelsin:
import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
df=df.index=df["age"]
df.index
#Yaş, index olarak eklendi

Float64Index([22.0, 38.0, 26.0, 35.0, 35.0,  nan, 54.0,  2.0, 27.0, 14.0,
              ...
              33.0, 22.0, 28.0, 25.0, 39.0, 27.0, 19.0,  nan, 26.0, 32.0],
             dtype='float64', name='age', length=891)

In [43]:
#Artık age bilgisi index yerinde, değişkenlerden yaşı sil:
import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
df.drop("age", axis=1)
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
df=df.drop("age", axis=1).head()

In [35]:
#Yaşı, değişkenlerden kalıcı olarak silmek için :
df.drop("age", axis=1, inplace=True)
df.head()

survived  pclass     sex  sibsp  parch     fare embarked  class    who  \
0         0       3    male      1      0   7.2500        S  Third    man   
1         1       1  female      1      0  71.2833        C  First  woman   
2         1       3  female      0      0   7.9250        S  Third  woman   
3         1       1  female      1      0  53.1000        S  First  woman   
4         0       3    male      0      0   8.0500        S  Third    man   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False  
1       False    C    Cherbourg   yes  False  
2       False  NaN  Southampton   yes   True  
3       False    C  Southampton   yes  False  
4        True  NaN  Southampton    no   True

In [34]:
#Indexi değişkene çevirmek için :
#df["x"] ifadesinde, değişkenlerde x varsa onu seçer, yoksa yeni değişken oluşturur.
df["age"] = df.index
df.head()

survived  pclass     sex  age  sibsp  parch     fare embarked  class  \
0         0       3    male    0      1      0   7.2500        S  Third   
1         1       1  female    1      1      0  71.2833        C  First   
2         1       3  female    2      0      0   7.9250        S  Third   
3         1       1  female    3      1      0  53.1000        S  First   
4         0       3    male    4      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [44]:
#2. yol : index i silip, değişken olarak ekler : RESET
df.reset_index().head()
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [ ]:
###############Değişkenşer üzerinde işlemler
#Kısaltma noktalarından kurtulmak için:
import pandas as pd
import seaborn as sns
pd.set_options("display.max_columns", None)
df=sns.load_dataset("titanic")
df.head()

In [49]:
#Bu değişken df içinde var mı?
"age" in df

True

In [50]:
#Bu seçimin sonucu bir pandas serisi, df değil
type(df["age"].head())

pandas.core.series.Series

In [51]:
#df olarak kalması için:
type(df[["age"]].head())

pandas.core.frame.DataFrame

In [52]:
#Birden fazla değişken seçmek:
df[["age", "alive"]].head

<bound method NDFrame.head of       age alive
0    22.0    no
1    38.0   yes
2    26.0   yes
3    35.0   yes
4    35.0    no
..    ...   ...
886  27.0    no
887  19.0   yes
888   NaN    no
889  26.0   yes
890  32.0    no

[891 rows x 2 columns]>

In [55]:
#Listedeki değişkenleri seçmek:
col_names=["age", "adult_male", "alive"]
df[col_names]

age  adult_male alive
0    22.0        True    no
1    38.0       False   yes
2    26.0       False   yes
3    35.0       False   yes
4    35.0        True    no
..    ...         ...   ...
886  27.0        True    no
887  19.0       False   yes
888   NaN       False    no
889  26.0        True   yes
890  32.0        True    no

[891 rows x 3 columns]

In [56]:
type(df[col_names])

pandas.core.frame.DataFrame

In [58]:
#df e değişken ekleme: yaşın karelerinden oluşan age2 değişkeni eklendi
df["age2"]= df["age"]**2
df.head(3)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone    age2  
0    man        True  NaN  Southampton    no  False   484.0  
1  woman       False    C    Cherbourg   yes  False  1444.0  
2  woman       False  NaN  Southampton   yes   True   676.0

In [60]:
df["age3"]= df["age2"] / df["age"]
df.head(3)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone    age2  age3  
0    man        True  NaN  Southampton    no  False   484.0  22.0  
1  woman       False    C    Cherbourg   yes  False  1444.0  38.0  
2  woman       False  NaN  Southampton   yes   True   676.0  26.0

In [62]:
#df den Değişken silme (kalıcı değil)
df.drop("age3", axis=1).head(3)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone    age2  
0    man        True  NaN  Southampton    no  False   484.0  
1  woman       False    C    Cherbourg   yes  False  1444.0  
2  woman       False  NaN  Southampton   yes   True   676.0

In [63]:
df.drop(col_names, axis=1).head(3)

survived  pclass     sex  sibsp  parch     fare embarked  class    who  \
0         0       3    male      1      0   7.2500        S  Third    man   
1         1       1  female      1      0  71.2833        C  First  woman   
2         1       3  female      0      0   7.9250        S  Third  woman   

  deck  embark_town  alone    age2  age3  
0  NaN  Southampton  False   484.0  22.0  
1    C    Cherbourg  False  1444.0  38.0  
2  NaN  Southampton   True   676.0  26.0

In [66]:
#Belli bir string ifadeyi barındıran değişkenleri seçmek : contains
df.loc[:, df.columns.str.contains("age")].head(3)

age    age2  age3
0  22.0   484.0  22.0
1  38.0  1444.0  38.0
2  26.0   676.0  26.0

In [67]:
#Belli bir string ifadeyi barındıran değişkenler dışındakileri seçmek : ~
df.loc[:, ~df.columns.str.contains("age")].head(3)

survived  pclass     sex  sibsp  parch     fare embarked  class    who  \
0         0       3    male      1      0   7.2500        S  Third    man   
1         1       1  female      1      0  71.2833        C  First  woman   
2         1       3  female      0      0   7.9250        S  Third  woman   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False  
1       False    C    Cherbourg   yes  False  
2       False  NaN  Southampton   yes   True

In [71]:
#######iloc : intager based selection
#satırlardan 0 dan 3 kadar elemanları seçmek
df.iloc[0:3]

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone    age2  age3  
0    man        True  NaN  Southampton    no  False   484.0  22.0  
1  woman       False    C    Cherbourg   yes  False  1444.0  38.0  
2  woman       False  NaN  Southampton   yes   True   676.0  26.0

In [69]:
df[0:0]

Empty DataFrame
Columns: [survived, pclass, sex, age, sibsp, parch, fare, embarked, class, who, adult_male, deck, embark_town, alive, alone, age2, age3]
Index: []

In [72]:
#loc: label based selection- 3 dahil
df.loc[0:3]

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   

     who  adult_male deck  embark_town alive  alone    age2  age3  
0    man        True  NaN  Southampton    no  False   484.0  22.0  
1  woman       False    C    Cherbourg   yes  False  1444.0  38.0  
2  woman       False  NaN  Southampton   yes   True   676.0  26.0  
3  woman       False    C  Southampton   yes  False  1225.0  35.0

In [73]:
#satırlarda ve sutunlarda 0 dan 3 e kadar seç
df.iloc[0:3, 0:3]

survived  pclass     sex
0         0       3    male
1         1       1  female
2         1       3  female

In [74]:
#Değerlerin bizzat kendilerine göre seçim yapmak için loc. 
#Satırlarda da label based. 3 dahil.
df.loc[0:3, "age"]

0    22.0
1    38.0
2    26.0
3    35.0
Name: age, dtype: float64

In [75]:
col_names=["age", "embarked", "alive"]
df.loc[0:3, col_names]

age embarked alive
0  22.0        S    no
1  38.0        C   yes
2  26.0        S   yes
3  35.0        S   yes

In [79]:
##############Koşullu Seçim
#Yaşı 50 den büyük olanları seçelim
#Tek bir değişken seçmediğin içi,n tüm değişkenlerde yaşı 50 den büyük olanı verdi
df[df["age"]>50].head(3)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
6          0       1    male  54.0      0      0  51.8625        S   First   
11         1       1  female  58.0      0      0  26.5500        S   First   
15         1       2  female  55.0      0      0  16.0000        S  Second   

      who  adult_male deck  embark_town alive  alone    age2  age3  
6     man        True    E  Southampton    no   True  2916.0  54.0  
11  woman       False    C  Southampton   yes   True  3364.0  58.0  
15  woman       False  NaN  Southampton   yes   True  3025.0  55.0

In [82]:
#Yaşı 50 den büyük kaçkişi var?
df[df["age"]>50].count()

survived       64
pclass         64
sex            64
age            64
sibsp          64
parch          64
fare           64
embarked       63
class          64
who            64
adult_male     64
deck           33
embark_town    63
alive          64
alone          64
age2           64
age3           64
dtype: int64

In [83]:
df[df["age"]>50]["age"].count()

64

In [86]:
#Bir koşul ve bir değişken seçme
#Yaşı 50 den büyük olan kişilerin yolculuk sınıfı 
#!! Label based bir seçim yapılacak :loc
df.loc[df["age"]>50, "class"].head()

6      First
11     First
15    Second
33    Second
54     First
Name: class, dtype: category
Categories (3, object): ['First', 'Second', 'Third']

In [88]:
#Yaşı 50 den büyük olan kişilerin yolculuk sınıfı ve yaşı 
df.loc[df["age"]>50, ["class", "age"]].head()

class   age
6    First  54.0
11   First  58.0
15  Second  55.0
33  Second  66.0
54   First  65.0

In [94]:
#İki koşula göre seçmek
#koşulları paranteze al !
#yaşı 50 den büyük erkekleri getir:
df.loc[(df["age"]>50) & (df["sex"]== "male")].head(3)

survived  pclass   sex   age  sibsp  parch     fare embarked   class  who  \
6          0       1  male  54.0      0      0  51.8625        S   First  man   
33         0       2  male  66.0      0      0  10.5000        S  Second  man   
54         0       1  male  65.0      0      1  61.9792        C   First  man   

    adult_male deck  embark_town alive  alone    age2  age3  
6         True    E  Southampton    no   True  2916.0  54.0  
33        True  NaN  Southampton    no   True  4356.0  66.0  
54        True    B    Cherbourg    no  False  4225.0  65.0

In [95]:
#tüm değişkenler değil yaş ve sınıf gelsin
df.loc[(df["age"]>50) & (df["sex"]== "male"),["age", "class"]].head(3)

age   class
6   54.0   First
33  66.0  Second
54  65.0   First

In [108]:
#Yaşı 50 den büyük, Cherbourg dan binen erkek yolcuların yaşı, sınıfı ve embark town u gelsin:
df.loc[(df["age"]>50) 
       & (df["sex"]== "male")
       & (df["embark_town"]=="Cherbourg"),
       ["age", "class", "embark_town"]].head(3)

age  class embark_town
54   65.0  First   Cherbourg
96   71.0  First   Cherbourg
155  51.0  First   Cherbourg

In [109]:
#Yaşı 50 den büyük, Cherbourg dan ya da Southampton dan binen erkek yolcuların yaşı, sınıfı ve embark town u gelsin:
import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
df.loc[(df["age"]>50) 
       & (df["sex"]== "male")
       & ((df["embark_town"]=="Cherbourg") | (df["embark_town"]=="Southampton")),
       ["age", "class", "embark_town"]].head(3)


age   class  embark_town
6   54.0   First  Southampton
33  66.0  Second  Southampton
54  65.0   First    Cherbourg

In [110]:
df["embark_town"].value_counts()

Southampton    644
Cherbourg      168
Queenstown      77
Name: embark_town, dtype: int64

In [111]:
#### Toplulaştırma ve Gruplama (Aggregation and Grouping)
df["age"].mean()

29.69911764705882

In [112]:
#Kadınların ve erkeklerin yaş ortalaması
#Cinsiyet kırılımında yaş değişkeninin ortalaması
df.groupby("sex")["age"].mean()

sex
female    27.915709
male      30.726645
Name: age, dtype: float64

In [113]:
#Cinsiyete göre yaş ortalaması için önerilen yol :
df.groupby("sex").agg({"age" : "mean"})

age
sex              
female  27.915709
male    30.726645

In [114]:
#cinsiyet kırılımında yaşlara ortalama, toplam gibi liste içinde olan elemanları uygulama
df.groupby("sex").agg({"age" : ["mean", "sum"]})

age          
             mean       sum
sex                        
female  27.915709   7286.00
male    30.726645  13919.17

In [115]:
#cinsiyete göre yaş ortalama ve toplamları, cinsiyete göre hayatta kalma ortalaması isteniyor
df.groupby("sex").agg({"age" : ["mean", "sum"],
                      "survived": "mean"})

age            survived
             mean       sum      mean
sex                                  
female  27.915709   7286.00  0.742038
male    30.726645  13919.17  0.188908

In [120]:
#3 kırılımlı
df.groupby(["sex", "embark_town", "class"]).agg({
    "age" : ["mean", "sum"],
    "survived": "mean",
    "sex": "count"})

age           survived   sex
                                mean      sum      mean count
sex    embark_town class                                     
female Cherbourg   First   36.052632  1370.00  0.976744    43
                   Second  19.142857   134.00  1.000000     7
                   Third   14.062500   225.00  0.652174    23
       Queenstown  First   33.000000    33.00  1.000000     1
                   Second  30.000000    30.00  1.000000     2
                   Third   22.850000   228.50  0.727273    33
       Southampton First   32.704545  1439.00  0.958333    48
                   Second  29.719697  1961.50  0.910448    67
                   Third   23.223684  1765.00  0.375000    88
male   Cherbourg   First   40.111111  1444.00  0.404762    42
                   Second  25.937500   207.50  0.200000    10
                   Third   25.016800   625.42  0.232558    43
       Queenstown  First   44.000000    44.00  0.000000     1
                   Second  57.000000    57.00  0.000000     1
                   Third   28.142857   394.00  0.076923    39
       Southampton First   41.897188  2681.42  0.354430    79
                   Second  30.875889  2778.83  0.154639    97
                   Third   26.574766  5687.00  0.128302   265

In [4]:
####Pivot Table
#Kesişimlerde survived, satırlarda cinsiyet ve sutunlarda embarked olsun
#Kesişimlerde survived ın ortalaması var. default = mean
import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
df.pivot_table("survived", "sex", "embarked")

embarked         C         Q         S
sex                                   
female    0.876712  0.750000  0.689655
male      0.305263  0.073171  0.174603

In [5]:
#Öntanımlı değeri standard sapma yap. Kesişimde std:
df.pivot_table("survived", "sex", "embarked", aggfunc="std")

embarked         C         Q         S
sex                                   
female    0.331042  0.439155  0.463778
male      0.462962  0.263652  0.380058

In [14]:
#Sutunlara daha çok değişken yerleştirmek:
df.pivot_table("survived", "sex", ["embarked", "class"])

embarked         C                      Q                          S  \
class        First Second     Third First Second     Third     First   
sex                                                                    
female    0.976744    1.0  0.652174   1.0    1.0  0.727273  0.958333   
male      0.404762    0.2  0.232558   0.0    0.0  0.076923  0.354430   

embarked                      
class       Second     Third  
sex                           
female    0.910448  0.375000  
male      0.154639  0.128302

In [16]:
#Yaş değişkenine göre hayatta kalmaya bakacağız. 
#1. adım: Sayısal değişkeni kategorik değişkene çevirmeye çalışalım
#Sayısal değişkenin bölüneceği aralıklar biliniyorsa : cut
import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
df["new_age"]=pd.cut(df["age"], [0, 10, 18, 25, 40, 90])
df.head(3)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone   new_age  
0    man        True  NaN  Southampton    no  False  (18, 25]  
1  woman       False    C    Cherbourg   yes  False  (25, 40]  
2  woman       False  NaN  Southampton   yes   True  (25, 40]

In [17]:
#2. adım :yaş aralığı ve cinsiyet  kırılımına göre survive
#Kesişimde ortalama survive, satırlarda cinsiyet ve sutunlarda yaş aralığı

df.pivot_table("survived", "sex", "new_age")

new_age   (0, 10]  (10, 18]  (18, 25]  (25, 40]  (40, 90]
sex                                                      
female   0.612903  0.729730  0.759259  0.802198  0.770833
male     0.575758  0.131579  0.120370  0.220930  0.176471

In [18]:
#Sutunlarda daha çok değişken
df.pivot_table("survived", "sex", ["new_age", "class"])

new_age (0, 10]                   (10, 18]                   (18, 25]  \
class     First Second     Third     First Second     Third     First   
sex                                                                     
female      0.0    1.0  0.500000  1.000000    1.0  0.523810  0.941176   
male        1.0    1.0  0.363636  0.666667    0.0  0.103448  0.333333   

new_age                      (25, 40]                      (40, 90]            \
class      Second     Third     First    Second     Third     First    Second   
sex                                                                             
female   0.933333  0.500000  1.000000  0.906250  0.464286  0.961538  0.846154   
male     0.047619  0.115385  0.513514  0.071429  0.172043  0.280000  0.095238   

new_age            
class       Third  
sex                
female   0.111111  
male     0.064516

In [20]:
#Çıktıyı yan yana görmek için
pd. set_option("display.width", 500)

In [23]:
#################Lambda ve Apply^
#Apply:satır ya da sutunlarda otomatik olarak fonksiyonu calıştırır
df["age2"]=df["age"]*2
df["age3"]=df["age"]*5

#içinde "age" geçen değişkenleri 10 a böl:
df[["age", "age2", "age3"]].apply(lambda x: x/10).head(3)

age  age2  age3
0  2.2   4.4  11.0
1  3.8   7.6  19.0
2  2.6   5.2  13.0

In [29]:
#loc ile satırlardan tümü, sutunlardan yaş ı barındıranı seç : contains
import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
df["age2"]=df["age"]*2
df["age3"]=df["age"]*5
df.loc[:, df.columns.str.contains("age")].apply(lambda x: x / 10).head(3)

age  age2  age3
0  2.2   4.4  11.0
1  3.8   7.6  19.0
2  2.6   5.2  13.0

In [30]:
#İçinde age olan değişkenleri seç,tüm gözlem birimlerinden ortalamayı çıkarıp std a böl:
df.loc[:, df.columns.str.contains("age")].apply(lambda x: (x - x.mean()) / x.std()).head(3)

age      age2      age3
0 -0.530005 -0.530005 -0.530005
1  0.571430  0.571430  0.571430
2 -0.254646 -0.254646 -0.254646

In [31]:
#Fonksiyonu dışarda tanımşayıp uygulamak :
def standard_scaler(col_name):
    return (col_name - col_name.mean())/ col_name.std()
df.loc[:, df.columns.str.contains("age")].apply(standard_scaler).head(3)

age      age2      age3
0 -0.530005 -0.530005 -0.530005
1  0.571430  0.571430  0.571430
2 -0.254646 -0.254646 -0.254646

In [ ]:
#"age" içeren değişkenlere yaptığımız bu değişiklikleri kaydetmek istiyoruz
df.loc[:, ["age", "age2", "age3"]]=df.loc[:, df.columns.str.contains("age")].apply(standard_scaler)

In [35]:
#age içereni otomatik seçmek :

df.loc[:, df.columns.str.contains("age")]=df.loc[:, df.columns.str.contains("age")].apply(standard_scaler)
df.head()

survived  pclass     sex       age  sibsp  parch     fare embarked  class    who  adult_male deck  embark_town alive  alone      age2      age3
0         0       3    male -0.530005      1      0   7.2500        S  Third    man        True  NaN  Southampton    no  False -0.530005 -0.530005
1         1       1  female  0.571430      1      0  71.2833        C  First  woman       False    C    Cherbourg   yes  False  0.571430  0.571430
2         1       3  female -0.254646      0      0   7.9250        S  Third  woman       False  NaN  Southampton   yes   True -0.254646 -0.254646
3         1       1  female  0.364911      1      0  53.1000        S  First  woman       False    C  Southampton   yes  False  0.364911  0.364911
4         0       3    male  0.364911      0      0   8.0500        S  Third    man        True  NaN  Southampton    no   True  0.364911  0.364911

In [ ]:
#######Birleştirme İşlemleri

In [20]:
import numpy as np
import pandas as pd
import seaborn as sns
m= np.random.randint(1, 30, size=(5,3))
df1=pd.DataFrame(m, columns=["var1", "var2", "var3"])
df1

var1  var2  var3
0     1     7    24
1     1    11    29
2    29     3    13
3    11     8    15
4    16    21     1

In [21]:
df2=df1+99
df2

var1  var2  var3
0   100   106   123
1   100   110   128
2   128   102   112
3   110   107   114
4   115   120   100

In [22]:
#İki df i birleştirmek : pd.comcat
pd.concat([df1, df2])

var1  var2  var3
0     1     7    24
1     1    11    29
2    29     3    13
3    11     8    15
4    16    21     1
0   100   106   123
1   100   110   128
2   128   102   112
3   110   107   114
4   115   120   100

In [ ]:
#concat la sutunlara göre de birleştirme yapabiliriz. 


In [23]:
#Merge ile birleştirme işlemelri 
df1=pd.DataFrame({"employees": ["jhon", "dennise", "mark", "maria"], 
                  "group": ["accounting", "engineering", "engineering", "hr"]})

df2=pd.DataFrame({"employees": ["jhon", "dennise", "mark", "maria"],
                  "start_date": [2010, 2009, 2014, 2019]})

pd.merge(df1,df2)
#belirtilmese de ortak olan employee ye göre birleştirme yapıldı

employees        group  start_date
0      jhon   accounting        2010
1   dennise  engineering        2009
2      mark  engineering        2014
3     maria           hr        2019

In [24]:
#neye göre birleştireceğini belirtmek:
df3=pd.merge(df1,df2, on="employees")

In [26]:
df4=pd.DataFrame({"group": ["accounting", "engineering", "hr"], 
                  "manager": ["Caner", "Mustafa", "Berkcan"]})

pd.merge(df3, df4)

employees        group  start_date  manager
0      jhon   accounting        2010    Caner
1   dennise  engineering        2009  Mustafa
2      mark  engineering        2014  Mustafa
3     maria           hr        2019  Berkcan

In [28]:
#1. Görev:
import seaborn as sns
import pandas as pd
df=sns.load_dataset("car_crashes")
["NUM"+ col.upper() if df[col].dtype == "0" else "NUM" + col for col in df.columns ]

TypeError: data type '' not understood

In [ ]:
#2.görev:
import seaborn as sns
import pandas as pd
df=sns.load_dataset("car_crashes")
[ "FLAG " + col.upper() if "no" not in col else col.upper() for col in df.columns ]

In [16]:
#3.görev
import seaborn as sns
import pandas as pd
df=sns.load_dataset("car_crashes")
og_list = ["abbrev", "no_previous"]
new_cols=[col for col in df.columns if col != og_list]
print(new_cols)
new_df=df[new_cols]
new_df.head(3)

['total', 'speeding', 'alcohol', 'not_distracted', 'no_previous', 'ins_premium', 'ins_losses', 'abbrev']


total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   

   ins_losses abbrev  
0      145.08     AL  
1      133.93     AK  
2      110.35     AZ

In [4]:
#PANDAS
#Görev 1-2
import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
df["sex"].value_counts()

male      577
female    314
Name: sex, dtype: int64

In [29]:
#Görev 3
# her sutunun unique değerlerin sayısı ?
import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
[df[col].unique() for col in df.columns]

[array([0, 1], dtype=int64),
 array([3, 1, 2], dtype=int64),
 array(['male', 'female'], dtype=object),
 array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
         4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
         8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
        49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
        16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
        71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
        51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
        45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
        60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
        70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ]),
 array([1, 0, 3, 4, 2, 5, 8], dtype=int64),
 array([0, 1, 2, 5, 3, 4, 6], dtype=int64),
 array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
         51.8625,  21.075 ,  11.1333

In [31]:
#Görev 4: pclass değişkeninin unique değerleri bulunuz.
df["pclass"].unique()

array([3, 1, 2], dtype=int64)

In [8]:
#Görev 5:pclass ve parch değişkenlerinin unique değerlerinin sayısını
df[["pclass","parch"]].nunique()

pclass    3
parch     7
dtype: int64

In [9]:
#not :
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


In [6]:
# ! Görev 6: embarked değişkeninin tipini kontrol ediniz. Tipini category olarak değiştiriniz. Tekrar tipini kontrol ediniz.
df["embarked"].dtype

dtype('O')

In [12]:
df["embarked"] = df["embarked"].astype("category")
str(df["embarked"].dtype)

'category'

In [10]:
#Not: dtype ve type farkı ne?
type(df["embarked"])

pandas.core.series.Series

In [7]:
#Not str ile yazmak için:
str(df["embarked"].dtype)


'object'

In [17]:
#! Görev 7: embarked denğeri C olanların tüm bilgelerini gösteriiz.
import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
df[df["embark_town"]=="Cherbourg"].head(3)

#Soru: "C" olarak yazınca gelmiyor

survived  pclass     sex   age  sibsp  parch     fare embarked   class    who  adult_male deck embark_town alive  alone
1          1       1  female  38.0      1      0  71.2833        C   First  woman       False    C   Cherbourg   yes  False
9          1       2  female  14.0      1      0  30.0708        C  Second  child       False  NaN   Cherbourg   yes  False
19         1       3  female   NaN      0      0   7.2250        C   Third  woman       False  NaN   Cherbourg   yes   True

In [17]:
# Görev 8: embarked değeri S olmayanların tüm bilgelerini
import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
df[df["embark_town"]!="Southampton"].head(3)
df[~(df["embarked"] == "S")]

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
1         1       1  female  38.0      1      0  71.2833        C   First   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck embark_town alive  alone  
1  woman       False    C   Cherbourg   yes  False  
5    man        True  NaN  Queenstown    no   True  
9  child       False  NaN   Cherbourg   yes  False

In [18]:
# Görev 9: Yaşı 30 dan küçük ve kadın olan yolcuların tüm bilgilerini
import seaborn as sns
df=sns.load_dataset("titanic")
df.loc[(df["age"]<30) & (df["sex"]== "female")].head(3)
#2. yol : (df[(df["age"] < 30) & (df["sex"] == "female")])

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
2         1       3  female  26.0      0      0   7.9250        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
2  woman       False  NaN  Southampton   yes   True  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

In [30]:
#Görev 10: Fare'i 500'den büyük veya yaşı 70 den büyük yolcuların bilgilerin
import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
df.loc[(df["fare"]>500) | (df["age"]>70)]
#df[(df["fare"] > 500) | (df["age"] > 70)].head()

survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
96          0       1    male  71.0      0      0   34.6542        C  First   
116         0       3    male  70.5      0      0    7.7500        Q  Third   
258         1       1  female  35.0      0      0  512.3292        C  First   
493         0       1    male  71.0      0      0   49.5042        C  First   
630         1       1    male  80.0      0      0   30.0000        S  First   
679         1       1    male  36.0      0      1  512.3292        C  First   
737         1       1    male  35.0      0      0  512.3292        C  First   
851         0       3    male  74.0      0      0    7.7750        S  Third   

       who  adult_male deck  embark_town alive  alone  
96     man        True    A    Cherbourg    no   True  
116    man        True  NaN   Queenstown    no   True  
258  woman       False  NaN    Cherbourg   yes   True  
493    man        True  NaN    Cherbourg    no   True  
630    man        True    A  Southampton   yes   True  
679    man        True    B    Cherbourg   yes  False  
737    man        True    B    Cherbourg   yes   True  
851    man        True  NaN  Southampton    no   True

In [20]:
# Görev 11: Her bir değişkendeki boş değerlerin toplamını bulunuz.
import seaborn as sns
df=sns.load_dataset("titanic")
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [21]:
# Görev 12: who değişkenini dataframe'den düşürün.
import seaborn as sns
df=sns.load_dataset("titanic")
df.drop("who", axis=1, inplace=True)
df.head(3)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False  
1       False    C    Cherbourg   yes  False  
2       False  NaN  Southampton   yes   True

In [19]:
# Görev 13: deck değikenindeki boş değerleri deck değişkenin en çok tekrar eden değeri (mode) ile doldurunuz.
import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
df["deck"].mode()
df["deck"].fillna(value="C", inplace=True)
df["deck"].isnull().sum()

0

In [8]:
#Görev 14: age değikenindeki boş değerleri age değişkenin medyanı ile doldurun.
import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
df["age"].fillna(df["age"].median(), inplace=True)
df["age"].isnull().sum()

0

In [10]:
# Görev 15: survived değişkeninin Pclass ve Cinsiyet değişkenleri kırılımınında sum, count, mean değerlerini bulunuz.
df.groupby(["pclass", "sex"]).agg({"survived": ["sum", "count", "mean"]})

survived                
                   sum count      mean
pclass sex                            
1      female       91    94  0.968085
       male         45   122  0.368852
2      female       70    76  0.921053
       male         17   108  0.157407
3      female       72   144  0.500000
       male         47   347  0.135447

In [7]:
# Görev 16:  30 yaşın altında olanlar 1, 30'a eşit ve üstünde olanlara 0 vericek bir fonksiyon yazınız.
# Yazdığınız fonksiyonu kullanarak titanik veri setinde age_flag adında bir değişken oluşturunuz oluşturunuz. (apply ve lambda yapılarını kullanınız)import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
df["age_flag"]=df["age"].apply(lambda y:1 if y<30 else 0)
df.head(3)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone  age_flag  
0    man        True  NaN  Southampton    no  False         1  
1  woman       False    C    Cherbourg   yes  False         0  
2  woman       False  NaN  Southampton   yes   True         1

In [11]:
# Görev 17: Seaborn kütüphanesi içerisinden Tips veri setini tanımlayınız.
import pandas as pd
import seaborn as sns
df=sns.load_dataset("tips")

In [3]:
# Görev X: Seaborn kütüphanesi içerisinden Tips veri setini tanımlayınız.
import pandas as pd
import seaborn as sns
df=sns.load_dataset("tips")
df[(df["size"]<3) & (df["total_bill"] >10)].mean()

total_bill    17.184965
tip            2.638811
size           1.993007
dtype: float64

In [12]:
# Görev 18: Time değişkeninin kategorilerine (Dinner, Lunch) göre total_bill  değerlerinin toplamını, min, max ve ortalamasını bulunuz.
import pandas as pd
import seaborn as sns
df=sns.load_dataset("tips")
df.groupby("time").agg({"total_bill": ["sum", "min", "max", "mean"]})

total_bill                        
              sum   min    max       mean
time                                     
Lunch     1167.47  7.51  43.11  17.168676
Dinner    3660.30  3.07  50.81  20.797159

In [13]:
# Görev 19: Günlere ve time göre total_bill değerlerinin toplamını, min, max ve ortalamasını bulunuz.
import pandas as pd
import seaborn as sns
df=sns.load_dataset("tips")
df.head(3)
df.groupby(["day", "time"]).agg({"total_bill": ["sum", "min", "max", "mean"]})

total_bill                         
                   sum    min    max       mean
day  time                                      
Thur Lunch     1077.55   7.51  43.11  17.664754
     Dinner      18.78  18.78  18.78  18.780000
Fri  Lunch       89.92   8.58  16.27  12.845714
     Dinner     235.96   5.75  40.17  19.663333
Sat  Lunch         NaN    NaN    NaN        NaN
     Dinner    1778.40   3.07  50.81  20.441379
Sun  Lunch         NaN    NaN    NaN        NaN
     Dinner    1627.16   7.25  48.17  21.410000

In [2]:
#Görev 20 :Lunch zamanına ve kadın müşterilere ait total_bill ve tip  değerlerinin day'e göre toplamını, 
import pandas as pd
import seaborn as sns
df=sns.load_dataset("tips")

df[(df["sex"] == "Female") & (df["time"] == "Lunch")].groupby("day").agg({
    "total_bill": ["sum", "min", "max", "mean"],
    "tip": ["sum", "min", "max", "mean"]})

total_bill                            tip                      
            sum    min    max      mean    sum   min   max      mean
day                                                                 
Thur     516.11   8.35  43.11  16.64871  79.42  1.25  5.17  2.561935
Fri       55.76  10.09  16.27  13.94000  10.98  2.00  3.48  2.745000
Sat        0.00    NaN    NaN       NaN   0.00   NaN   NaN       NaN
Sun        0.00    NaN    NaN       NaN   0.00   NaN   NaN       NaN

In [14]:
#Görev 21: size'i 3'ten küçük, total_bill'i 10'dan büyük olan siparişlerin ortalaması nedir?
#NE ORTALAMASI?
import pandas as pd
import seaborn as sns
df=sns.load_dataset("tips")
df[(df["size"]<3) & (df["total_bill"] >10)].mean()

total_bill    17.184965
tip            2.638811
size           1.993007
dtype: float64

In [15]:
# Görev 22: total_bill_tip_sum adında yeni bir değişken oluşturun. Her bir müşterinin ödediği totalbill ve tip in toplamını versin.
import pandas as pd
import seaborn as sns
df=sns.load_dataset("tips")
df["total_bill_tip_sum"]= df["total_bill"] + df["tip"]
df.head()

total_bill   tip     sex smoker  day    time  size  total_bill_tip_sum
0       16.99  1.01  Female     No  Sun  Dinner     2               18.00
1       10.34  1.66    Male     No  Sun  Dinner     3               12.00
2       21.01  3.50    Male     No  Sun  Dinner     3               24.51
3       23.68  3.31    Male     No  Sun  Dinner     2               26.99
4       24.59  3.61  Female     No  Sun  Dinner     4               28.20

In [26]:
# Görev 23: total_bill_tip_sum değişkenine göre büyükten küçüğe sıralayınız ve ilk 30 kişiyi yeni bir dataframe'e atayınız.
import pandas as pd
import seaborn as sns
df=sns.load_dataset("tips")
df["total_bill_tip_sum"]= df["total_bill"] + df["tip"]
new_df = df.sort_values("total_bill_tip_sum", ascending=False)[:30].reset_index(drop=True)
df.head()

total_bill   tip     sex smoker  day    time  size  total_bill_tip_sum
0       16.99  1.01  Female     No  Sun  Dinner     2               18.00
1       10.34  1.66    Male     No  Sun  Dinner     3               12.00
2       21.01  3.50    Male     No  Sun  Dinner     3               24.51
3       23.68  3.31    Male     No  Sun  Dinner     2               26.99
4       24.59  3.61  Female     No  Sun  Dinner     4               28.20

In [ ]:
#Not:
pd.set_option("display.width", 500)
pd.set_option("display.max_rows", None)

In [2]:
import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
pd.set_option("display.width", 500)
pd.set_option("display.max_rows", None)
df.head(3)

survived  pclass     sex   age  sibsp  parch     fare embarked  class    who  adult_male deck  embark_town alive  alone
0         0       3    male  22.0      1      0   7.2500        S  Third    man        True  NaN  Southampton    no  False
1         1       1  female  38.0      1      0  71.2833        C  First  woman       False    C    Cherbourg   yes  False
2         1       3  female  26.0      0      0   7.9250        S  Third  woman       False  NaN  Southampton   yes   True